# Generated by Django 5.2 on 2025-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Middlename', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Lastname', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor')], default='Doctor', max_length=20)),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
